# Generated by Django 4.0.4 on 2022-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='idle', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='idle', max_length=30),
        ),
    ]
