# Generated by Django 4.0.4 on 2022-05-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_alter_game_status_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('active', 'Active')], default='idle', max_length=30),
        ),
    ]
