# Generated by Django 4.0.4 on 2022-05-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_1_mark',
            field=models.CharField(choices=[('circle', 'Circle'), ('cross', 'Cross')], default='circle', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2_mark',
            field=models.CharField(choices=[('circle', 'Circle'), ('cross', 'Cross')], default='cross', max_length=30),
        ),
    ]
