# Generated by Django 3.2.13 on 2022-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_auto_20220515_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_2_mark',
            new_name='opponent_mark',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_1_mark',
            new_name='owner_mark',
        ),
    ]
